name: curvenote
on:
  pull_request:
    branches: ['main']
permissions:
  contents: read
  pull-requests: write
jobs:
  publish:
    uses: curvenote/actions/.github/workflows/publish.yml@v1
    with:
      monorepo: true
      # The pattern is helpful if you require authors to create their own unique ID
      # This must be globally unique in Curvenote, please prefix it with your venue if you enforce it
      id-pattern-regex: '^example-(?:[a-zA-Z0-9-_]{3,25})$'
      enforce-single-folder: article
      preview-label: article
      submit-label: article
      # Update this to your venue
      venue: cn-testing
      # collection: ''
      kind: Article
      path: articles/*
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
